
# This file is automatically generated, you probably don't want to edit this

RjOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "RjOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            code = "\n# summary(data[1:3])\n",
            R = NULL,
            vars = NULL,
            output = NULL,
            figWidth = "",
            figHeight = "",
            toggle = NULL, ...) {

            super$initialize(
                package='Rj',
                name='Rj',
                requiresData=TRUE,
                ...)

            private$..code <- jmvcore::OptionString$new(
                "code",
                code,
                default="\n# summary(data[1:3])\n",
                hidden=TRUE)
            private$..R <- jmvcore::OptionList$new(
                "R",
                R,
                hidden=TRUE,
                options=list(
                    "bundled",
                    "external"))
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                hidden=TRUE,
                permitted=list(
                    "factor",
                    "numeric",
                    "id"))
            private$..output <- jmvcore::OptionList$new(
                "output",
                output,
                hidden=TRUE,
                options=list(
                    "noEcho",
                    "echo"))
            private$..figWidth <- jmvcore::OptionString$new(
                "figWidth",
                figWidth,
                default="",
                hidden=TRUE)
            private$..figHeight <- jmvcore::OptionString$new(
                "figHeight",
                figHeight,
                default="",
                hidden=TRUE)
            private$..toggle <- jmvcore::OptionBool$new(
                "toggle",
                toggle,
                hidden=TRUE)

            self$.addOption(private$..code)
            self$.addOption(private$..R)
            self$.addOption(private$..vars)
            self$.addOption(private$..output)
            self$.addOption(private$..figWidth)
            self$.addOption(private$..figHeight)
            self$.addOption(private$..toggle)
        }),
    active = list(
        code = function() private$..code$value,
        R = function() private$..R$value,
        vars = function() private$..vars$value,
        output = function() private$..output$value,
        figWidth = function() private$..figWidth$value,
        figHeight = function() private$..figHeight$value,
        toggle = function() private$..toggle$value),
    private = list(
        ..code = NA,
        ..R = NA,
        ..vars = NA,
        ..output = NA,
        ..figWidth = NA,
        ..figHeight = NA,
        ..toggle = NA)
)

RjResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="R")}))

RjBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "RjBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'Rj',
                name = 'Rj',
                version = c(1,0,0),
                options = options,
                results = RjResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Rj Editor
#'
#' 
#' @param data .
#' @param code .
#' @param R .
#' @param vars .
#' @param output .
#' @param figWidth .
#' @param figHeight .
#' @param toggle .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
Rj <- function(
    data,
    code = "\n# summary(data[1:3])\n",
    R,
    vars,
    output,
    figWidth = "",
    figHeight = "",
    toggle) {

    if ( ! requireNamespace('jmvcore'))
        stop('Rj requires jmvcore to be installed (restart may be required)')

    if (missing(data))
        data <- jmvcore:::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))

    options <- RjOptions$new(
        code = code,
        R = R,
        vars = vars,
        output = output,
        figWidth = figWidth,
        figHeight = figHeight,
        toggle = toggle)

    results <- RjResults$new(
        options = options)

    analysis <- RjClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
