
# This file is automatically generated, you probably don't want to edit this

RjpOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "RjpOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            code = "\nsummary(data)\n",
            R = "bundled",
            vars = NULL,
            output = "noEcho",
            figWidth = "",
            figHeight = "",
            toggle = FALSE, ...) {

            super$initialize(
                package="Rj",
                name="Rjp",
                requiresData=TRUE,
                ...)

            private$..code <- jmvcore::OptionString$new(
                "code",
                code,
                default="\nsummary(data)\n",
                hidden=TRUE)
            private$..R <- jmvcore::OptionList$new(
                "R",
                R,
                hidden=TRUE,
                options=list(
                    "bundled",
                    "external"),
                default="bundled")
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                permitted=list(
                    "factor",
                    "numeric",
                    "id"))
            private$..output <- jmvcore::OptionList$new(
                "output",
                output,
                hidden=TRUE,
                options=list(
                    "noEcho",
                    "echo"),
                default="noEcho")
            private$..figWidth <- jmvcore::OptionString$new(
                "figWidth",
                figWidth,
                default="",
                hidden=TRUE)
            private$..figHeight <- jmvcore::OptionString$new(
                "figHeight",
                figHeight,
                default="",
                hidden=TRUE)
            private$..toggle <- jmvcore::OptionBool$new(
                "toggle",
                toggle,
                default=FALSE,
                hidden=TRUE)

            self$.addOption(private$..code)
            self$.addOption(private$..R)
            self$.addOption(private$..vars)
            self$.addOption(private$..output)
            self$.addOption(private$..figWidth)
            self$.addOption(private$..figHeight)
            self$.addOption(private$..toggle)
        }),
    active = list(
        code = function() private$..code$value,
        R = function() private$..R$value,
        vars = function() private$..vars$value,
        output = function() private$..output$value,
        figWidth = function() private$..figWidth$value,
        figHeight = function() private$..figHeight$value,
        toggle = function() private$..toggle$value),
    private = list(
        ..code = NA,
        ..R = NA,
        ..vars = NA,
        ..output = NA,
        ..figWidth = NA,
        ..figHeight = NA,
        ..toggle = NA)
)

RjpResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "RjpResults",
    inherit = jmvcore::Group,
    active = list(
        createdColumns = function() private$.items[["createdColumns"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="R")
            self$add(jmvcore::Output$new(
                options=options,
                name="createdColumns",
                initInRun=TRUE))}))

RjpBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "RjpBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "Rj",
                name = "Rjp",
                version = c(1,0,0),
                options = options,
                results = RjpResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Rj Editor +
#'
#' 
#' @param data .
#' @param code .
#' @param R .
#' @param vars .
#' @param output .
#' @param figWidth .
#' @param figHeight .
#' @param toggle .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$createdColumns} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
Rjp <- function(
    data,
    code = "\nsummary(data)\n",
    R = "bundled",
    vars,
    output = "noEcho",
    figWidth = "",
    figHeight = "",
    toggle = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("Rjp requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- RjpOptions$new(
        code = code,
        R = R,
        vars = vars,
        output = output,
        figWidth = figWidth,
        figHeight = figHeight,
        toggle = toggle)

    analysis <- RjpClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

